### ISSUE TITLE
potential resource leak

### ISSUE THREAD

**Issue by baloo** [parallaxsecond/rust-tss-esapi#198]
When running tests with swtpm (0.5.2) linked with libtpms(0.8.0). I'm seeing a lot of:
```
WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:390:Esys_StartAuthSession_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode (0x00000903)
[2021-02-27T04:12:22Z ERROR tss_esapi::context::tpm_commands::session_commands] Error when creating a session: out of memory for session contexts
WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:390:Esys_StartAuthSession_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode (0x00000903)
[2021-02-27T04:12:22Z ERROR tss_esapi::context::tpm_commands::session_commands] Error when creating a session: out of memory for session contexts
WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:390:Esys_StartAuthSession_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode (0x00000903)
[2021-02-27T04:12:22Z ERROR tss_esapi::context::tpm_commands::session_commands] Error when creating a session: out of memory for session contexts

---- test_create_ak_rsa_rsa stdout ----
thread 'test_create_ak_rsa_rsa' panicked at 'called `Result::unwrap()` on an `Err` value: Tss2Error(FormatZero(FormatZeroResponseCode { .0: 2307, error_number: 3, format_selector: false, version: true, tcg_vendor_indicator: false, severity: true }))', tss-esapi/tests/abstraction_ak_tests.rs:31:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/core/src/option.rs:1300:5
   3: core::result::Result<T,E>::unwrap
             at /nix/store/wd3x41h39smq4js8ds0jbl35jxnydxvm-rust-1.52.0-nightly-2021-02-25-98f8cce6d/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: abstraction_ak_tests::test_create_ak_rsa_rsa
             at ./tests/abstraction_ak_tests.rs:23:5
   5: abstraction_ak_tests::test_create_ak_rsa_rsa::{{closure}}
             at ./tests/abstraction_ak_tests.rs:19:1
   6: core::ops::function::FnOnce::call_once
             at /nix/store/wd3x41h39smq4js8ds0jbl35jxnydxvm-rust-1.52.0-nightly-2021-02-25-98f8cce6d/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_create_and_use_ak stdout ----
thread 'test_create_and_use_ak' panicked at 'called `Result::unwrap()` on an `Err` value: Tss2Error(FormatZero(FormatZeroResponseCode { .0: 2307, error_number: 3, format_selector: false, version: true, tcg_vendor_indicator: false, severity: true }))', tss-esapi/tests/abstraction_ak_tests.rs:68:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/core/src/option.rs:1300:5
   3: core::result::Result<T,E>::unwrap
             at /nix/store/wd3x41h39smq4js8ds0jbl35jxnydxvm-rust-1.52.0-nightly-2021-02-25-98f8cce6d/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: abstraction_ak_tests::test_create_and_use_ak
             at ./tests/abstraction_ak_tests.rs:60:19
   5: abstraction_ak_tests::test_create_and_use_ak::{{closure}}
             at ./tests/abstraction_ak_tests.rs:55:1
   6: core::ops::function::FnOnce::call_once
             at /nix/store/wd3x41h39smq4js8ds0jbl35jxnydxvm-rust-1.52.0-nightly-2021-02-25-98f8cce6d/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Should I restart the TPM, the tests go further, but still crash at some point.
This is how I start my swtpm:
https://github.com/baloo/reproducibility-lab/blob/baloo/wip/pcr-eventlog-attestation/pkgs/pcr-eventlog-attestation/shell.nix#L152

This would look like a resources leak of some sort.

**Comment by Superhepper** [comment]
Yes, we have this for a while I think. Some tests just never seem to work when running them locally (i.e. running them for a second time on a machine). So my guess is that it is some kind if permanent handle that does not get removed. I have not been looking closely at this though so I am just guessing. It would be really nice if it could be fixed though. The first thing I would do here in this test would be to remove the ```unwrap()``` to ```expect()``` so it gets easier to see what went wrong.

**Comment by baloo** [comment]
I triggered the issue elsewhere. A `tpm2 flushcontext --transient-object` fixed it.

**Comment by ionut-arm** [comment]
I have previously seen this, thought it was solved 😕 damn... We are leaking sessions somewhere, will try and rat it out at some point.

**Comment by ionut-arm** [comment]
Ok, turns out something like this happens in the Parsec service sometimes, but it's due to how the service handles signals.

@baloo - did the `tpm2_flushcontext` fix it permanently? I can run all the tests multiple times in a row with no failure due to sessions sticking around

**Comment by baloo** [comment]
no, but after a flush context I could re-run the tests again.

**Comment by ionut-arm** [comment]
Hey - is that one of our unit tests? If not, could you post a link to/copy of the test?

**Comment by DNJha** [comment]
Hi @ionut-arm, It's one of the tests I wrote. It actually tries to make the context static for further use. 

You can find the minimal function and test on [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=18be342a57ea524ce54e8dea301d246c)

The test executes successfully for 3 times and then fails for the remaining time.

Any help is appreciated.

**Comment by kcking** [comment]
This could be because you are storing `Context` in a static variable, which will prevent [`Context::drop`](https://docs.rs/tss-esapi/latest/src/tss_esapi/context.rs.html#443-478) from running on program exit. Note that [`D::drop`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=576cf10039c6fde5f5266a578a320d04) never runs in this example.

Instead of storing `Context` in a static, what about passing around an `Arc<Mutex>`, which should one drop once the last reference to it is dropped.

**Comment by Superhepper** [comment]
What version of the rust-tss-esapi is this? If possible could you run it with latest from master and see what the error says?
I am guessing that the things mentioned above are the most likely causes. 

But I think I should point out that I have also seen problems with ```Esys_StartAuthSession``` in the `ek`and the `ak` functions when the TPM software simulator have been built with a smaller amount of memory. I was trying to find the cause of this at one point but was unable to exactly find anything.
